### ISSUE TITLE
How do we get started?

### ISSUE THREAD

**Issue by robyurkowski** [grounded/afterburnercms#1]
Hey, everyone, and formally welcome to the project. We need a spot to collect discussions on this project and on the framework ([afterburner](/parndt/afterburner)), and this seems like as good a spot as any to track it, since we'll all get notifications here.

Here's what the plan is: we want to build a top-notch CMS backed by a framework that manages the complexity of hot-swappable parts. 

(So, for example, we might want to use `kaminari` as a default paginator, but it should be up to the user whether he'd rather swap in `will_paginate`. That's not to say we will write the code to make will_paginate work, but there will be a protocol to which users can adapt `will_paginate` that will enable it to work as a drop-in.)

Now that Rails engines aren't cutting edge, it's become noticeable that there are a lot of trouble spots that every engine has to deal with in order to remain a good citizen. The Afterburner framework should also deal with these.

(For example, here, Forem and Spree both decouple authentication from themselves, and let the user set their own, even though the latter includes its own default.)

There are a few things you can read to get up to speed.

[This Gist](https://gist.github.com/3ce6f7e356dbec63c6f0) elaborates on what was perceived to be the core features at the time of project conception. This list probably should change and be settled here, now that we have more stakeholders present. We definitely do need to come to a consensus quickly about what we want to do with this, though I think we're relatively close.

[The open issues on Afterburner](https://github.com/grounded/afterburner/issues?page=1&state=open) should also be worthy of a look, since those were early thoughts that should be translated over.

I think that's a good start. Introduce yourself!

**Comment by robyurkowski** [comment]
So, @knewter and I spoke for a bit tonight and started trying to iron out a few things in terms of our domain and our basic APIs. Here's a [rough draft](https://gist.github.com/robyurkowski/5d8434d29c77abb6c8b5) -- comments very much appreciated.

**Comment by robyurkowski** [comment]
Okay, everyone. I've now populated a whole swackton of issues. Keeping in mind that lower-numbered issues are more likely to be used in higher-numbered issues, pick your favourite, and let's go to town.

If you have any questions, don't hesitate to ask.

**Comment by parndt** [comment]
How is a swackton measured?

**Comment by robyurkowski** [comment]
It's approximately equivalent to four bucketloads and seven eighths a shit-ton.
