### ISSUE TITLE
Baseline Decisions

### ISSUE THREAD

**Issue by parndt** [grounded/afterburnercms#2]
Continuing discussion from parndt/afterburner#7

**Comment by radar** [comment]
The fact that this issue was created before #7 and is "continuing discussion" from it is blowing my mind.

**Comment by radar** [comment]
Oh, different repository. I see what you did there.

**Comment by parndt** [comment]
It's a different repo, broseph

**Comment by robyurkowski** [comment]
Okay, finally found an example why I think HAML is a substantial timesaver.

Compare these two lines:

``` erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(newsletter) -%>">
```

``` haml
%li.clearfix.record{:class => cycle("on", "on-hover"), :id => dom_id(newsletter)}
```

Not only is that a bit more clear, but you can actually pass an array to :class and it will append them properly. This could be written like this, too:

``` haml
%li{:class => [cycle("on", "on-hover"), 'clearfix', 'record'], :id => dom_id(newsletter)}
```

So much cleaner. String interpretation is the devil, and having to concatenate CSS classes or accept whitespace in your markup is a terrible choice to have to make.
