### ISSUE TITLE
As a Developer, I should be able to set a custom mount point for the administrative section and the CMS itself

### ISSUE THREAD

**Issue by robyurkowski** [grounded/afterburnercms#22]
So I could move the actual admin section to, say, `/afterburner`, instead of `/admin` or whatever similar convention we come up with. And likewise, so instead of mounting at the root of an app, ABC plays the good citizen and can be mounted at `/cms` or `/pages`.

**Comment by parndt** [comment]
What about if you want to mount every piece at different points?

**Comment by robyurkowski** [comment]
What other mountable pieces are you thinking of?

...

Must resist urge to snicker.

**Comment by parndt** [comment]
Like mount the blog at /blog and the news feed at /current_events that sort of thing 

Rather than /cms/blog and /cms/current_events

MAXIMUM FLEXIBILITY

but this means we can't steal the routes

**Comment by robyurkowski** [comment]
I think this is largely covered by #14, with the obvious caveat that if you're mounting the CMS to a non-root partition, all your CMS stuff, including blog will be mounted under that.

**Comment by parndt** [comment]
With Rails, you can't have it both ways. Either you mount each one separately so that you can mount Blog outside of the CMS subdir (/cms) as /blog or you force everything the CMS includes to be inside the namespace, a la /cms/blog

**Comment by robyurkowski** [comment]
I mean to say that we should mount all the front-end inside the CMS's mount point, so if it's at /cms, blog is at /cms too. Like I said, though, within that /cms space, you can pretty much set your own vanity URLs.

What do you guys think, @radar @knewter @GeekOnCoffee @gogogarrett @ugisozols?

**Comment by knewter** [comment]
I don't know of an easy way in rails to mount them at different places but it seems desirable.  At any rate, I guess you would Just Not Mount at /cms if you want sensible looking urls.  For instance, you could mount at /app or /site and it wouldn't look so dumb maybe?

**Comment by robyurkowski** [comment]
I guess you could just mount each engine separately, right? But that'd lead to a clusterf**\* of a routes.rb file for most sites...

**Comment by knewter** [comment]
at present we have achieved this with frontend and backend engines, right @robyurkowski ?

**Comment by robyurkowski** [comment]
Yessir!

**Comment by robyurkowski** [comment]
Added by 3843129392b.

**Comment by robyurkowski** [comment]
Actually, one thing left on this is documentation. Someone feel like volunteering?

**Comment by knewter** [comment]
I'm on it.

**Comment by robyurkowski** [comment]
:heart: :+1:

_Rob Yurkowski_
Freelance Web Developer | Currently Available for Consultation
rob@yurkowski.net | @robyurkowski https://www.twitter.com/robyurkowski |
705 . 919 . 4476

**Comment by knewter** [comment]
Documented in #58.  Also your sig in the comment box is hilarious

**Comment by knewter** [comment]
Closed by #58
