### ISSUE TITLE
As a content creator, I want to be able to have my browser crash without losing changes

### ISSUE THREAD

**Issue by GeekOnCoffee** [grounded/afterburnercms#36]
Saving drafts are one approach, there's also http://simsalabim.github.com/sisyphus/ which uses HTML5 magic to make it work

**Comment by robyurkowski** [comment]
Ah, that's definitely an interesting idea! :+1: on this, though where it should be milestoned is a good question.

**Comment by robyurkowski** [comment]
Okay, this is definitely not MVP functionality. In fact, it's so low priority it's not funny. I'm actually of the opinion that this is plugin-worthy, so I'm closing this to be implemented third-party.
