### ISSUE TITLE
Bake in spring?

### ISSUE THREAD

**Issue by parndt** [grounded/afterburnercms#38]
Related to #37 https://github.com/jonleighton/spring

**Comment by robyurkowski** [comment]
No strong opinion. Honestly, sub-10s tests don't bother me. Maybe it would if I were working on the rails part more... but at the moment, I'm not bothered in the slightest.

**Comment by parndt** [comment]
More than 1 second seriously bothers me.
I aint mad but I aint trollin either

**Comment by knewter** [comment]
:+1:

**Comment by johanb** [comment]
I was all :+1: when I saw the title, but then I realized you weren't talking about [this Spring](http://www.springsource.org/).. so now I'm all :-1: < /trolling >

**Comment by parndt** [comment]
At least initially I'm closing this. We're not overly concerned with the delivery mechanism.
