### ISSUE TITLE
API Docs are ugly as sin

### ISSUE THREAD

**Issue by robyurkowski** [grounded/afterburnercms#41]
Can we find a way to make our docs look way nicer -- maybe like Dragonfly's?

**Comment by knewter** [comment]
Yard is how dragonfly does it. <3 yard.

**Comment by robyurkowski** [comment]
And we use YARD too, but the default YARD template is still stupid and awful to navigate. Take a look at how [Dragonfly does it](http://markevans.github.com/dragonfly/).

**Comment by knewter** [comment]
yeah, I see where he overrides the YARD doc layouts.  I'm just going to yank his templates for now and add a note somewhere thanking him for them?  He's MIT licensed, shouldn't be a problem.

**Comment by robyurkowski** [comment]
Sounds good, but I'm not particularly fussed atm. This is about as low priority as it can get.

**Comment by knewter** [comment]
addressed in #57
