### ISSUE TITLE
Make it possible for datastores to use host app's database

### ISSUE THREAD

**Issue by robyurkowski** [grounded/afterburnercms#68]
Also, how the heck should we deal with migrations / creating tables?!

**Comment by knewter** [comment]
@robyurkowski what's the status here?  I landed some code that can do this (but needs to be extracted to `afterburner-rails-shared`?) and you handled the migrations in rails as well?

**Comment by robyurkowski** [comment]
I think we're good, yeah. There's some more work needed to make this work with more than Postgres on your end, yeah? But everything else is AOK.
